spring:
  profiles:
    active: ${PROFILE:local}

  datasource:
    url: jdbc:mysql://${MAIN_MYSQL_HOST}:${MAIN_DB_PORT}/${MAIN_DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false&rewriteBatchedStatements=true
    username: ${MAIN_MYSQL_USERNAME}
    password: ${MAIN_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true

juso:
  api:
    base-url: ${JUSO_API_BASE_URL:https://business.juso.go.kr/api/jst/download}
